### ISSUE TITLE
Missing key B420FD3777CCE3A7F0076B55nch668DF69375001, which is needed to vey.sy signature.

### ISSUE THREAD

**Issue by oshitaka** [kpcyrd/spotify-launcher#70] opened 2024-12-28 06:51 UTC
Merry holidays!

Faced with this error when tied to launch

```
spotify-launcher -v
[2024-12-28T06:24:01Z DEBUG spotify_launcher::config] Searching for configuration file at "/home/oshitaka/.config/spotify-launcher.conf"
[2024-12-28T06:24:01Z DEBUG spotify_launcher::config] Searching for configuration file at "/etc/spotify-launcher.conf"
[2024-12-28T06:24:01Z DEBUG spotify_launcher::config] Found configuration file at "/etc/spotify-launcher.conf"
[2024-12-28T06:24:01Z INFO  spotify_launcher::config] Loading configuration file at"/etc/spotify-launcher.conf"
[2024-12-28T06:24:01Z DEBUG spotify_launcher] Using install path: "/home/oshitaka/.local/share/spotify-launcher/install"
[2024-12-28T06:24:01Z DEBUG spotify_launcher::paths] Reading state file from "/home/
oshitaka/.local/share/spotify-launcher/state.json"...
[2024-12-28T06:24:01Z DEBUG spotify_launcher::paths] Loaded state: Ok(State { version: "1:1.2.52.442.g01893f92", last_update_check: SystemTime { tv_sec: 1734982560, tv_nsec: 294917635 } })
[2024-12-28T06:24:01Z DEBUG spotify_launcher] Last update check was 4 days and 10 hours ago
[2024-12-28T06:24:01Z INFO  spotify_launcher::apt] Downloading release file...
[2024-12-28T06:24:01Z DEBUG spotify_launcher::http] Fetching "http://repository.spotify.com/dists/testing/Release"...
[2024-12-28T06:24:01Z DEBUG spotify_launcher::http] Fetched 2447 bytes
[2024-12-28T06:24:01Z INFO  spotify_launcher::apt] Downloading signature...[2024-12-28T06:24:01Z DEBUG spotify_lau
er::http] Fetching "http://repositor
potify.com/dists/testing/Release.gpg
.
[2024-12-28T06:24:01Z DEBUG spotify_launcher::http] Fetched 833 bytes
[2024-12-28T06:24:01Z INFO  spotify_launcher::apt] Verifying pgp signature...
Missing key B420FD3777CCE3A7F0076B55nch668DF69375001, which is needed to vey.sy signature.                        "..Error: Verification of pgp signature didn't succeed
```

**Comment by mohak34** [comment] 2024-12-28 07:22
yes even i got this when i tried to launch spotify

**Comment by kpcyrd** [comment] 2024-12-28 11:57
Duplicate of #67, this is fixed in the latest version of Arch Linux.

**Closed by kpcyrd** 2024-12-28 11:57 UTC
